<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SmartGrader.Image</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartGrader.Core\SmartGrader.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>
</Project>
